#! /usr/bin/env python3

import os
import sys

root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path = [os.path.join(root_dir, "src")] + sys.path

from lmcrec.playback.commands.lmcrec_check_index import main

if __name__ == "__main__":
    sys.exit(main())
