#!/bin/bash --noprofile

this_script=${0##*/}
    
usage="
Usage: $this_script [-f|--force]

Apply release tag locally and to the remote. Requires
a clean git status. Use --force to reapply the tag.

"
force=
case "$1" in
    -h|--h*)
        echo >&2 "$usage"
        exit 1
        ;;
    -f|--force)
        force="--force"
        shift
        ;;
esac

this_dir=$(dirname $(realpath $0))

set -e
cd $this_dir

# Must be in in proper git state:
./check-git-state

# Get semver:
. release-definitions.sh

# Apply release tag:
git tag $force $release_tag
git push $force origin tag $release_tag 
