#!/bin/bash --noprofile

# Infer project root from invocation:
this_script=${0##*/}
case "$0" in
    /*|*/*) this_dir=$(dirname $(realpath $0));;
    *) this_dir=$(dirname $(realpath $(which $0)));;
esac

set -e
cd $this_dir

# Source definitions:
. release-definitions.sh

# Generate release files:
(
    set -ex
    mkdir -p $release_dir
    rm -rf $release_dir/*
    ./lmcrec/create-release-files
    ./lmcpb/create-release-files
)

echo
echo "$this_script - Release created under $(realpath $release_dir)"
