#!/bin/bash --noprofile

# All paths next are relative to the location of this script:
bin_subdir=bin
go_os_arch_file=go-os-arch-targets.txt
scripts_subdir=scripts
staging_dir=staging

# Infer script name and location from invocation:
this_script=${0##*/}
case "$0" in
    /*|*/*) this_dir=$(dirname $(realpath $0));;
    *) this_dir=$(dirname $(realpath $(which $0)));;
esac

set -e
cd $this_dir

. ../release-definitions.sh

(
    set -ex
    ./go-build-all -t $go_os_arch_file
)

(
    set -ex
    mkdir -p $release_dir
)
while read os arch; do
    [[ "$os" = '#'* || -z "$os" || -z "$arch" ]] && continue

    os_arch="$os-$arch"
    os_arch_staging_dir=$staging_dir/$os_arch
    pkg_os_arch="$pkg_dir-$os_arch"
    pkg_os_arch_ver="$os-$arch-$semver"
    (
        set -ex

        rm -rf $staging_dir/$os-$arch/$release
        mkdir -p $staging_dir/$os-$arch/$release


        cp -p $relnotes_file $staging_dir/$os-$arch/$release
        mkdir -p $staging_dir/$os-$arch/$release/bin/$os-$arch
        cp -p bin/$os-$arch/lmcrec* $staging_dir/$os-$arch/$release/bin/$os-$arch
    )
    for src_dir in $reference_dir scripts; do
        dst_dir=$staging_dir/$os-$arch/$release/$(basename $src_dir)
        (
            set -ex
            rsync -plrtHS \
                ${rsync_exclude_file:+--exclude-from=}$rsync_exclude_file \
                $src_dir/ $dst_dir
        )
    done
    archive=$release_dir/$release-$os-$arch.tgz
    (
        set -x

        rm -f $staging_dir/$os-$arch/$release_prefix
        ln -fs $release $staging_dir/$os-$arch/$release_prefix

        mkdir -p $release_dir
        tar czf $release_dir/$release-$os-$arch.tgz -C $staging_dir/$os-$arch --no-xattrs $release_prefix $release

        rm -rf $staging_dir/$os-$arch/*
    )
    echo "$this_script: $(realpath $archive) created"
done < $go_os_arch_file


