// Prompt: .github/prompts/encoder_info_file_tc_test.go.prompt.md
// Model: Claude Sonnet 4.5

package codec

import "time"

var EncoderInfoFileNoErrTestCases = []*EncoderInfoTestCase{
	{
		Name:        "SingleFlush",
		Description: "Single timestamp and tally followed by flush to verify basic info file creation",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 1024,
				ScanInInstCount: 10,
				ScanInVarCount:  50,
				ScanOutVarCount: 45,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "MultipleFlushes",
		Description: "Multiple timestamps and tallies with flushes after each to test incremental info file updates",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 512,
				ScanInInstCount: 5,
				ScanInVarCount:  25,
				ScanOutVarCount: 20,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 1, 0, 0, time.UTC),
				ScanInByteCount: 768,
				ScanInInstCount: 8,
				ScanInVarCount:  35,
				ScanOutVarCount: 30,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 2, 0, 0, time.UTC),
				ScanInByteCount: 1024,
				ScanInInstCount: 12,
				ScanInVarCount:  45,
				ScanOutVarCount: 40,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "NoFlushUntilEnd",
		Description: "Multiple timestamps and tallies without intermediate flushes to test final flush behavior",
		Version:     "1.1.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 256,
				ScanInInstCount: 3,
				ScanInVarCount:  15,
				ScanOutVarCount: 12,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 30, 0, time.UTC),
				ScanInByteCount: 512,
				ScanInInstCount: 6,
				ScanInVarCount:  28,
				ScanOutVarCount: 25,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 1, 0, 0, time.UTC),
				ScanInByteCount: 768,
				ScanInInstCount: 9,
				ScanInVarCount:  42,
				ScanOutVarCount: 38,
				DoFlush:         false,
			},
		},
	},
	{
		Name:        "MixedFlushPattern",
		Description: "Mixed pattern of flushes and no-flushes to test flexible info file update scenarios",
		Version:     "2.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 100,
				ScanInInstCount: 1,
				ScanInVarCount:  5,
				ScanOutVarCount: 4,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 15, 0, time.UTC),
				ScanInByteCount: 200,
				ScanInInstCount: 2,
				ScanInVarCount:  10,
				ScanOutVarCount: 8,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 30, 0, time.UTC),
				ScanInByteCount: 300,
				ScanInInstCount: 3,
				ScanInVarCount:  15,
				ScanOutVarCount: 12,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 45, 0, time.UTC),
				ScanInByteCount: 400,
				ScanInInstCount: 4,
				ScanInVarCount:  20,
				ScanOutVarCount: 16,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 1, 0, 0, time.UTC),
				ScanInByteCount: 500,
				ScanInInstCount: 5,
				ScanInVarCount:  25,
				ScanOutVarCount: 20,
				DoFlush:         true,
			},
		},
	},
	{
		Name:         "WithPrevFileName",
		Description:  "Test info file generation with previous file reference to verify linking capability",
		Version:      "1.2.0",
		PrevFileName: "/path/to/previous.lmcrec",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 9, 59, 0, 0, time.UTC),
				ScanInByteCount: 2048,
				ScanInInstCount: 20,
				ScanInVarCount:  100,
				ScanOutVarCount: 95,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "LargeTallyCounts",
		Description: "Test with large tally counts to verify handling of significant data volumes",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 100000,
				ScanInInstCount: 1000,
				ScanInVarCount:  5000,
				ScanOutVarCount: 4500,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 5, 0, 0, time.UTC),
				ScanInByteCount: 200000,
				ScanInInstCount: 2000,
				ScanInVarCount:  10000,
				ScanOutVarCount: 9000,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "ZeroTallyCounts",
		Description: "Test with zero tally counts to verify handling of empty scan results",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 0,
				ScanInInstCount: 0,
				ScanInVarCount:  0,
				ScanOutVarCount: 0,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 1, 0, 0, time.UTC),
				ScanInByteCount: 100,
				ScanInInstCount: 1,
				ScanInVarCount:  5,
				ScanOutVarCount: 4,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "FrequentSmallFlushes",
		Description: "Frequent flushes with small data increments to test high-frequency update scenarios",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 10,
				ScanInInstCount: 1,
				ScanInVarCount:  2,
				ScanOutVarCount: 1,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 1, 0, time.UTC),
				ScanInByteCount: 10,
				ScanInInstCount: 1,
				ScanInVarCount:  2,
				ScanOutVarCount: 1,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 2, 0, time.UTC),
				ScanInByteCount: 10,
				ScanInInstCount: 1,
				ScanInVarCount:  2,
				ScanOutVarCount: 1,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 3, 0, time.UTC),
				ScanInByteCount: 10,
				ScanInInstCount: 1,
				ScanInVarCount:  2,
				ScanOutVarCount: 1,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 4, 0, time.UTC),
				ScanInByteCount: 10,
				ScanInInstCount: 1,
				ScanInVarCount:  2,
				ScanOutVarCount: 1,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "LongRunningSession",
		Description: "Simulate a long-running session with periodic flushes over hours",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 5000,
				ScanInInstCount: 50,
				ScanInVarCount:  250,
				ScanOutVarCount: 200,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 11, 0, 0, 0, time.UTC),
				ScanInByteCount: 6000,
				ScanInInstCount: 60,
				ScanInVarCount:  300,
				ScanOutVarCount: 250,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 12, 0, 0, 0, time.UTC),
				ScanInByteCount: 7000,
				ScanInInstCount: 70,
				ScanInVarCount:  350,
				ScanOutVarCount: 300,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 13, 0, 0, 0, time.UTC),
				ScanInByteCount: 8000,
				ScanInInstCount: 80,
				ScanInVarCount:  400,
				ScanOutVarCount: 350,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "EmptyVersion",
		Description: "Test info file with empty version string to verify optional version handling",
		Version:     "",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 512,
				ScanInInstCount: 5,
				ScanInVarCount:  25,
				ScanOutVarCount: 20,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "CumulativeCounters",
		Description: "Test that tally counters accumulate correctly across multiple scans",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 100,
				ScanInInstCount: 10,
				ScanInVarCount:  50,
				ScanOutVarCount: 45,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 30, 0, time.UTC),
				ScanInByteCount: 150,
				ScanInInstCount: 15,
				ScanInVarCount:  75,
				ScanOutVarCount: 70,
				DoFlush:         false,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 1, 0, 0, time.UTC),
				ScanInByteCount: 200,
				ScanInInstCount: 20,
				ScanInVarCount:  100,
				ScanOutVarCount: 95,
				DoFlush:         true,
			},
		},
	},
	{
		Name:        "TimeProgressionCheck",
		Description: "Verify that mostRecentTs updates correctly with each timestamp",
		Version:     "1.0.0",
		TestData: []EncoderInfoTestData{
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 0, 0, 0, time.UTC),
				ScanInByteCount: 100,
				ScanInInstCount: 1,
				ScanInVarCount:  5,
				ScanOutVarCount: 4,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 5, 0, 0, time.UTC),
				ScanInByteCount: 200,
				ScanInInstCount: 2,
				ScanInVarCount:  10,
				ScanOutVarCount: 8,
				DoFlush:         true,
			},
			{
				Timestamp:       time.Date(2024, 1, 15, 10, 10, 0, 0, time.UTC),
				ScanInByteCount: 300,
				ScanInInstCount: 3,
				ScanInVarCount:  15,
				ScanOutVarCount: 12,
				DoFlush:         true,
			},
		},
	},
}
