#!/bin/bash --noprofile

this_script=${0##*/}

case "$1" in
    ""|-h*|--h*)
        echo >&2 "Usage: $this_script HELPER_DIR...|all"
        exit 1
    ;;
esac

case "$0" in
    /*|*/*) this_dir=$(realpath $(dirname $0));;
    *) this_dir=$(realpath $(dirname $(which $0)));;
esac

tests_dir=$(dirname $this_dir)
project_root_dir=$(dirname $tests_dir)
relpath_to_this_dir=${this_dir##$project_root_dir/}

set -e
cd $this_dir
if [[ "$*" == "all" ]]; then
    dir_list=$(\ls -1 */main.go | sed -e 's|/main.go||')
else
    dir_list="$*"
fi
for helper_dir in $dir_list; do
    helper_dir=${helper_dir%%/}
    [[ -f $helper_dir/dst_file ]] || continue
    dst_file=$tests_dir/$(cat $helper_dir/dst_file)
    (
        echo "# Generated by cd $relpath_to_this_dir && ./$this_script $helper_dir"
        echo
        echo "# noqa"
        echo "# isort: skip_file"
        echo "# fmt: off"
        cd $helper_dir && go run .
        echo "# fmt: on"
    ) > $dst_file
    echo "generated $dst_file"
done
