CREATE TABLE data_stream_src6_t (
    lmc_ts_col datetime,
    lmc_inst_col varchar(255),
    broadcast_col unsigned int,
    cache_drop_col unsigned int,
    cbr_info_col unsigned int,
    cbr_status_col unsigned int,
    change_request_id_col unsigned int,
    drop_sink_col unsigned int,
    generic_col unsigned int,
    group_merge_col unsigned int,
    group_status_col unsigned int,
    insert_ack_col unsigned int,
    insert_nak_col unsigned int,
    node_id_change_col unsigned int,
    permission_info_col unsigned int,
    refresh_data_col unsigned int,
    refresh_hdr_col unsigned int,
    refresh_latency_col unsigned int,
    refresh_rate_col unsigned int,
    rename_col unsigned int,
    set_group_col unsigned int,
    status_col unsigned int,
    total_col unsigned int,
    update_col unsigned int,
    update_latency_col unsigned int,
    update_rate_col unsigned int
)
